### ISSUE TITLE
Convert to TypeScript / homebridge-plugin-template base.

### ISSUE THREAD

**Issue by dsully** [senorshaun/homebridge-radiora2#1]
Hi - I was going to look at converting parts of this to use the current Homebridge Typescript based system.

Would you be willing to accept PRs for that?

Thanks

**Comment by senorshaun** [comment]
Sure thing. 
Personally I don’t see a big benefit to typescript but it seems like that’s the direction the community is moving in. 

On Sep 27, 2020, at 9:52 AM, Dan Sully <notifications@github.com> wrote:

﻿
Hi - I was going to look at converting parts of this to use the current Homebridge Typescript based system.

Would you be willing to accept PRs for that?

Thanks

**Comment by senorshaun** [comment]
haven't heard any reason to do this. closing out
