### ISSUE TITLE
Name parameter not working 

### ISSUE THREAD

**Issue by shawnparr** [senorshaun/homebridge-radiora2#10]
version 1.3.2,
config:

> {
>     "platform": "RadioRA2",
>     "name": "RadioRA2",
>     "repeater": "redacted",
>     "username": "redacted",
>     "password": "redacted",
>     "fans": [
>         {
>             "name": "Master Bedroom Fan",
>             "id": 18,
>             "adjustable": true,
>             "onvalue": 25
>         },
>         {
>             "name": "Den Fan",
>             "id": 35,
>             "adjustable": true,
>             "onvalue": 25
>         }
>     ],
>     "occupancysensors": [
>         {
>             "name": "Master Closet Occupancy",
>             "id": 25
>         }
>     ]
> }

In the logs I get:

> [10/31/2021, 3:45:40 PM] [RadioRA2] Connected to Lutron!
> (node:2141) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
>     at new Fan (/homebridge/node_modules/homebridge-radiora2/lib/accessories/fan.js:14:72)
>     at RadioRA2Platform.addFanAccessory (/homebridge/node_modules/homebridge-radiora2/index.js:57:44)
>     at RadioRA2Platform.<anonymous> (/homebridge/node_modules/homebridge-radiora2/index.js:211:30)
>     at Array.forEach (<anonymous>)
>     at RadioRA2Platform.<anonymous> (/homebridge/node_modules/homebridge-radiora2/index.js:206:23)
>     at RadioRa2.emit (events.js:400:28)
>     at incomingData (/homebridge/node_modules/homebridge-radiora2/lib/radiora2.js:97:20)
>     at Socket.<anonymous> (/homebridge/node_modules/homebridge-radiora2/lib/radiora2.js:27:92)
>     at Socket.emit (events.js:400:28)
>     at addChunk (internal/streams/readable.js:293:12)
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:2141) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)

If I remove the "name" entries I get the following:

> [10/31/2021, 3:52:04 PM] [RadioRA2] Connected to Lutron!
> [10/31/2021, 3:52:04 PM] [RadioRA2] Invalid fan in config. Not loading it.
> [10/31/2021, 3:52:04 PM] [RadioRA2] Invalid fan in config. Not loading it.
> [10/31/2021, 3:52:04 PM] [RadioRA2] Loaded 2 fan(s)
> [10/31/2021, 3:52:04 PM] [RadioRA2] Loaded 0 light(s)
> [10/31/2021, 3:52:04 PM] [RadioRA2] Invalid occupancy sensor in config. Not loading it.
> [10/31/2021, 3:52:04 PM] [RadioRA2] Loaded 1 occupancy sensor(s)
> [10/31/2021, 3:52:04 PM] [RadioRA2] Loaded 0 keypad(s)
> [10/31/2021, 3:52:04 PM] [RadioRA2] Loaded 0 visor control receiver(s)
> [10/31/2021, 3:52:04 PM] [RadioRA2] Loaded 0 HVAC controller(s)

**Comment by cariacou** [comment]
Same problem here. 
Can we just have the name be optional, with a default name filled in? 
Either Lutron's name / Model Number / Type or Lutron's ID would be good enough. It's easy to rename in HomeKit.

Right now I cannot get past the boot stage of the plugin.

**Comment by cariacou** [comment]
The model number is not optional. It is required. Could be anything, for example "RRD-PRO_via_homebridge", but can't be empty.

It would be a cool update if most parameters could be optional. I under the ID is required, but the rest could have a default value. For example:
- `model` could default to `homebridge_rr2_fan` / `homebridge_rr2_light`
- `name` could be a mix of Lutron's name, Model Number, Type or Lutron's ID. Not sure which of these are available. For example `fan 33` where ID=33.
