### ISSUE TITLE
Error when adding more than 2 keys to a keypad config: Warning unhandled rejection: TypeError: Cannot read properties of undefined (reading 'getCharacteristic')

### ISSUE THREAD

**Issue by jfinestone** [senorshaun/homebridge-radiora2#14]
We are using Hoobs
Tried adding a third key to the main-repeater "keypad"
and it errored out when restarting
See attached configs
here are the logs
we are trying to integrate with the "phantom keys" on the main-repeater, we have 45 of them (out of the 100 lutron supports) (eg 1-100 and leds 101-200)
thank you for your help!

note:
hoobs version 4.1.22
node version 16.13.2
homebridge version 1.4.0
plug in 1.3.4

logs with a working config with keypad with MAX of 2 keys on keypad(s):
2/5/2022, 5:00:55 PMRadiora2 BridgeConfiguration change
2/5/2022, 5:00:55 PMradiora2bridge stopping
2/5/2022, 5:00:56 PMRadiora2 BridgeRadioRA2Disconnecting
2/5/2022, 5:01:01 PMRadiora2 Bridge starting
2/5/2022, 5:01:09 PMRadiora2 BridgeLoaded plugin 'homebridge-radiora2'
2/5/2022, 5:01:10 PMRadiora2 BridgeLoading 2 platforms...
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Attempting connection to 192.168.4.78...
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Connecting...
2/5/2022, 5:01:10 PMRadiora2 BridgeBridge is running on port 51826.
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Connected to Lutron!
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Loaded fan 'Powder Fan'
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Loaded fan 'Kids Fan'
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Loaded fan 'Parents Fan'
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Loaded 3 fan(s)
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Loaded 0 light(s)
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Loaded 0 occupancy sensor(s)
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Loaded keypad 'Vestibule'
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Loaded keypad 'Main-Rep'
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Loaded keypad 'Main-Rep'
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Loaded 3 keypad(s)
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Loaded 0 visor control receiver(s)
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Loaded 0 HVAC controller(s)
2/5/2022, 5:01:10 PMRadiora2 BridgeRadioRA2Deleted removed accessory

when i added a third key to a keypad, it failed:
2/5/2022, 5:04:52 PMRadiora2 BridgeLoaded plugin 'homebridge-radiora2'
2/5/2022, 5:04:52 PMRadiora2 BridgeLoading 2 platforms...
2/5/2022, 5:04:52 PMRadiora2 BridgeRadioRA2Attempting connection to 192.168.4.78...
2/5/2022, 5:04:52 PMRadiora2 BridgeRadioRA2Connecting...
2/5/2022, 5:04:52 PMRadiora2 BridgeBridge is running on port 51826.
2/5/2022, 5:04:52 PMRadiora2 BridgeRadioRA2Connected to Lutron!
2/5/2022, 5:04:52 PMRadiora2 BridgeRadioRA2Loaded fan 'Powder Fan'
2/5/2022, 5:04:52 PMRadiora2 BridgeRadioRA2Loaded fan 'Kids Fan'
2/5/2022, 5:04:52 PMRadiora2 BridgeRadioRA2Loaded fan 'Parents Fan'
2/5/2022, 5:04:52 PMRadiora2 BridgeRadioRA2Loaded 3 fan(s)
2/5/2022, 5:04:52 PMRadiora2 BridgeRadioRA2Loaded 0 light(s)
2/5/2022, 5:04:52 PMRadiora2 BridgeRadioRA2Loaded 0 occupancy sensor(s)
2/5/2022, 5:04:52 PMRadiora2 BridgeRadioRA2Loaded keypad 'Vestibule'
2/5/2022, 5:04:52 PMRadiora2 BridgeWarningunhandled rejection: TypeError: Cannot read properties of undefined (reading 'getCharacteristic')

see attached
[when a third key is added stops working.txt](https://github.com/senorshaun/homebridge-radiora2/files/8010509/when.a.third.key.is.added.stops.working.txt)
[this config works.txt](https://github.com/senorshaun/homebridge-radiora2/files/8010510/this.config.works.txt)

**Comment by senorshaun** [comment]
good catch. we had no ability to add (or remove) buttons from existing keypads. version 1.3.5 was just published with this fix

**Comment by jfinestone** [comment]
Great.  Thanks.  Will test and let you know.
