### ISSUE TITLE
Pico / Shades

### ISSUE THREAD

**Issue by jfinestone** [senorshaun/homebridge-radiora2#17]
Hello. 

Are PICO remote supported?  It looks like someone developed a plug-in, but only for Caseta Pro https://github.com/rnilssoncx/homebridge-pico

would be great if we could have similar functionality, or at least capture a single button press of a PICO. 

The PICO have some significant limitations when you try to build functionality in software, so it be great if we could access it through Homebridge to build automations etc.

Are shades supported in your plug in?

Thanks.

**Comment by senorshaun** [comment]
Try the pico out as a stateless keypad with the buttons. I think as far as integration protocol it works that way? That’s off the top of my head. 

Shades, I haven’t gotten around to playing with as I don’t have a test motor 

On Feb 20, 2022, at 11:53 AM, jfinestone ***@***.***> wrote:

﻿
Hello.

Are PICO remote supported? It looks like someone developed a plug-in, but only for Caseta Pro https://github.com/rnilssoncx/homebridge-pico

would be great if we could have similar functionality, or at least capture a single button press of a PICO.

The PICO have some significant limitations when you try to build functionality in software, so it be great if we could access it through Homebridge to build automations etc.

Are shades supported in your plug in?

Thanks.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by jfinestone** [comment]
Pico integration appears to work as a keypad
Except that the button switches to "on" or "off" with every push of the
real button - and in reality, these buttons are always off.  Anyway for
them just to reflect the press and not a change in state?
One nice thing about that other plug-in is that it also accepts
"double-press" and "hold".  If you ever have time to incorporate those,
that would be great.  If you need a Pico, happy to send you one.

Also, if you ever have time to incorporate shades, would be appreciated.
We would be happy to test any progress you make.

Thanks.

**Comment by jfinestone** [comment]
Pico keypad shows up in Homekit
And clicking on button in Home toggles between on/off in Home - but
When stateless is false, sends a button press command to Lutron
When stateless is true, does not send a button press to Lutron
However, pressing the real Pico button does nothing to the button in Home (which is what I need it to do)

**Comment by senorshaun** [comment]
I took a second looking at this. Am I wrong in thinking that pico remotes are 'stateless' buttons? Like there is no on/off value for each button, only an on press event? Looking at the repo you sent, it looks like they are doing things the same way as me, with a stateless switch listener. I can update the stateless: true to accept button presses, thats not hard at all. I'm not readily seeing why stateless: true does not temporarily toggle the switch in the home app using this plugin. Hard for me to try to debug without a device (like a pico remote). I guess I could just rip out their code, but it would take some effort converting to all to my format. if that plugin is working for you, go for it. If I get my hands on a pico, I'll get around to incorporating it in to here after I can test.

As far as debugging, I believe you have to run HomeKit in debug mode for most of the low level stuff to show up. Not sure how to do that with HOOBS. [Maybe try this?](https://github.com/hoobs-org/HOOBS/issues/709)

**Comment by jfinestone** [comment]
It would be great to have this in your plug-in. For two reasons, first of
all the other plug-in does not specifically say it will work with RR2, so
it may break; and secondly I think it’s just better to have only one
integration between the platforms.

I attached some screenshots to show you what the other plug-in looks like.
On the home screen, it looks like a button/belly button. Pressing it takes
you to the configuration page, it does not send anything back to the Lutron
processor.  When you press the actual Pico key, The image of it depresses
just for a second and then it does whatever related HomeKit commands you
have. To configure the HomeKit commands, you click on it and it takes you
to that other page.

And yes, the pico is a stateless remote. It does have a tiny LED but it
only is on when you are pressing the button it does not function like the
LEDs on keypads.

Lastly it would be great if you could ever add shades to the mix. We would
like to not have any integration using the native integration.

I run home bridge on a Nas at my house, we run Hoobs at my buddy’s house. I
don’t ever get any debug or output from your plugin even though Debug is
true (no quotes)

**Comment by senorshaun** [comment]
I just got a little pico delivered for amazon. I'll check out that plugin and see what I can get worked in to this one. 
To be clear, you want the pico, in HomeKit, to status when the physical button is pressed? Presumably to run automations off of. Also it looks like you can customize that plugins' buttons to execute HomeKit actions when pressed. Rather than the other way around, like pressing the button in the HomeKit remote acts the same as pressing the button on the pico.
Now that I have it infront of me, and the plugin loaded up, let me know what you are wanting to be able to do

**Comment by jfinestone** [comment]
Correct. Pressing the button in HomeKit only brings up the configuration of
what you want all the buttons to do. It’s only real purpose is so you can
hit the physical button on the pico and then it launches something in
HomeKit.  Either for a single press, a double press, or a long press.
You’ll see there’s a lot of different configurations of picos.

**Comment by senorshaun** [comment]
I almost have a beta ready to test. Am I correct in saying that the Home app doesn’t display the names of buttons correctly?

**Comment by jfinestone** [comment]
Correct. They seem to all appear just as one button with no way to separate
them let me know if you need some additional screenshots

**Comment by senorshaun** [comment]
as far as functionality goes, it seems silly to me to have a double press and long press action for the increase/decrease buttons on the pico? Right? 
What are your thoughts?

**Comment by senorshaun** [comment]
I get you. I think you would have to connect the button a shortcut that gets the light value, then increases on 1 and set the light valve. Then that would need to get pushed over and over again to 'raise' the level of a light. So I went ahead and made any buttons longAction a parameter which by default is 'click'. but if you set it, on a per button level, to 'repeat', the long press button will get pressed repeatedly, every half second, for up to 100 clicks (thats from 0 to 100, I didn't want to get in to a situation when it just got pressed for forever because of some quirk where the plugin doesn't receive the release notification of the pico button). I think that should accomplish what you're wanting. Press once to go up 1%. Press and hold for 5 seconds to go up 10%. etc

**Comment by jfinestone** [comment]
That’s great. Looking forward to trying it.

**Comment by senorshaun** [comment]
ok I have a beta tested and released. I reloaded my normal config with it, nothing changed or broke with it, so you should be good to test it out.

npm install (-g if you use it) homebridge-radiora2@beta

`
                "keypads":[{
                        "name": "Pico",
                        "id": 39,
                        "stateless": true,
                        "buttons":[{
                                "name": "On",
                                "id": 2
                        },{
                                "name": "Off",
                                "id": 4,
                                "longpressrepeat": true
                        }]
                }]`
Making a keypad stateless is set on creation, so you have to remove the keypad from HomeKit and add it back if you want to change that.
Buttons are built on keypad creation so you have to remove the keypad from HomeKit and add it back if you want to add/remove buttons or change their name.
Other than name and id, all button config parameters are NOT set on creation, they are set the first time that button is pressed after homebridge has been started up. so you can make a change in your config and then just restart homebridge to see it. 

name - obvious
id -  obvious
longpressrepeat - default: false. set to true if you want the long press button in HomeKit to get pressed repeatedly when you hold the pico button
clicktime - default 500 this is how long the plugin will listen to determine single/double/hold. in milliseconds
repeattime - default 500 this is how often the plugin will press the button when repeating (only used when longpressrepeat = true). in milliseconds
repeatmax - default 100 this is how many times the plugin will press the held button


Let me know how it works out for you

**Comment by senorshaun** [comment]
@jfinestone  did you test this?

**Comment by jfinestone** [comment]
Waiting for Custom PICOs to arrive…
Thank you!

**Comment by senorshaun** [comment]
do you have any regular ones you can test with? so I can push from beta to prod?

**Comment by jfinestone** [comment]
I'll order one.  Thanks.

**Comment by senorshaun** [comment]
Sorry I thought you already had them and were using them with the caseta plugin?

**Comment by jfinestone** [comment]
I had one at another house - they are gone right now.  So I just ordered
one for my place (since the custom ones are 3-4 months out I found out last
week ugh).  Thanks.
What version of the module should I have loaded to test these and what
should the config be?
thanks.

**Comment by senorshaun** [comment]
check this comment https://github.com/senorshaun/homebridge-radiora2/issues/17#issuecomment-1065984532

**Comment by senorshaun** [comment]
these are working in 1.5.1
