### ISSUE TITLE
Occupancy Sensors

### ISSUE THREAD

**Issue by jfinestone** [senorshaun/homebridge-radiora2#18]
When adding Occupancy Sensors to the Config, do you use the integration ID for the occupancy sensor or the room?  From the integration guide, it seems like you would be getting this info from the room, which may include more than one occupancy sensor. 

For this house, which would we use:

Powder Room	 Powder Room Sensor	 Device 001	 LRF2-OCR2B-P-WH	17
Parents Bathroom	 MAster Bath Sensor	 Device 001	 LRF2-OCR2B-P-WH	18
Kids Bathroom	 Bath 3 Sensor	 Device 001	 LRF2-OCR2B-P-WH	19

Parents Bathroom	82
Kids Bathroom	86
Powder Room	78

Thanks.

**Comment by senorshaun** [comment]
Yes for occupancy sensors use the room id. Lutron reports the whole room as active when any occupancy sensor in that room detects motion and inactive when none do

so use 
Parents Bathroom 82
Kids Bathroom 86
Powder Room 78


dear lord you have a lot of rooms lol
