### ISSUE TITLE
GrafikEye Support 

### ISSUE THREAD

**Issue by aamiyazaki** [senorshaun/homebridge-radiora2#2]
Can you please add support to GrafikEye model QSGRJ-6PBA, or advise how to add it using the templates available

**Comment by senorshaun** [comment]
Did you try setting it up as a keypad and adding each button you want to expose?

On Oct 8, 2020, at 11:14 AM, Alberto Miyazaki <notifications@github.com> wrote:

﻿
Can you please add support to GrafikEye model QSGRJ-6PBA, or advise how to add it using the templates available

**Comment by senorshaun** [comment]
any update?
