### ISSUE TITLE
Multiple Buttons?

### ISSUE THREAD

**Issue by scoutbeer** [senorshaun/homebridge-radiora2#23]
I'm wondering if it is possible to expose multiple buttons for a Keypad.  I first tried with one button and was successful, i then tried to add a second button but I'm not able to get the second button to appear.

Relevant snippet below:

 _"keypads": [
                {
                    "name": "10 Button Keypad",
                    "id": 86,
                    "buttons": [
                        {
                            "name": "Test Button",
                            "id": 5,
                            "led": 85
                        },
                        {
                            "name": "Homekit Device",
                            "id": 6,
                            "led": 86
                        }
                    ]
                }
            ]_

**Comment by senorshaun** [comment]
They need to be added at the same time if I remember correctly. Delete your keypad from your config, restart homebridge so it clears the accessory. Add the keypad back with both buttons

On Jun 28, 2022, at 3:23 PM, scoutbeer ***@***.***> wrote:

﻿
I'm wondering if it is possible to expose multiple buttons for a Keypad. I first tried with one button and was successful, i then tried to add a second button but I'm not able to get the second button to appear.

Relevant snippet below:

"keypads": [
{
"name": "10 Button Keypad",
"id": 86,
"buttons": [
{
"name": "Test Button",
"id": 5,
"led": 85
},
{
"name": "Homekit Device",
"id": 6,
"led": 86
}
]
}
]

**Comment by scoutbeer** [comment]
Thanks for the quick reply.  I followed your guidance, remove the snippet of the config for the keypads, rebooted and noticed the button had successfully deleted.  I added back the config for the two buttons and when the plugin restarted it only added one button. I figured maybe something was still cached.  I removed the entire plugin including the bridge it was on.  Re-installed the plugin on its own bridge.  Rebooted again.  Added back all the config including the config for two buttons, and it still is only showing one button.

Snippet from Logs:
_6/28/2022, 3:47:26 PM Radiora2 BridgeLutron RA2 Loaded keypad '10 Button Keypad'
6/28/2022, 3:47:26 PM Radiora2 BridgeLutron RA2 Loaded 1 keypad(s)_

**Comment by senorshaun** [comment]
Sounds like when you remove the keypad it’s not deleting the accessory from the persist. 

On Jun 28, 2022, at 3:56 PM, scoutbeer ***@***.***> wrote:

﻿
Thanks for the quick reply. I followed your guidance, remove the snippet of the config for the keypads, rebooted and noticed the button had successfully deleted. I added back the config for the two buttons and when the plugin restarted it only added one button. I figured maybe something was still cached. I removed the entire plugin including the bridge it was on. Re-installed the plugin on its own bridge. Rebooted again. Added back all the config including the config for two buttons, and it still is only showing one button.

Snippet from Logs:
6/28/2022, 3:47:26 PM Radiora2 BridgeLutron RA2 Loaded keypad '10 Button Keypad'
6/28/2022, 3:47:26 PM Radiora2 BridgeLutron RA2 Loaded 1 keypad(s)

**Comment by scoutbeer** [comment]
I even cleared the cache on the bridge.  I'm not sure what else i can do the clear the 'persist'.

**Comment by senorshaun** [comment]
I’m not saying you should mess with this but there is a cachedAccessory file that saves all that info. Thats what would be cleared out.

What version of the plugin are you running?

**Comment by scoutbeer** [comment]
HOOBS 4.2.5 which uses Homebridge 1.4.1

**Comment by senorshaun** [comment]
Do you have a system that you can test out a beta on? I have cleaned up how a lot of stuff is saved. Also updated to have a UI to update the plugin accessories. and button to automatically pull the installed accessories from the repeater (as long as it wasn't set up as a walk around system). Update to the latest beta. This could remove some of your accessories (depending on how they were defined) on start up. let me know what you see please. I haven't had a chance to test everything, as I don't have some device types, but I think most is. I do know of one bug in the UI, the buttons on keypads don't all show up as tabs until you click on the next tab (you can see the name of your next installed button on that keypad).

**Comment by scoutbeer** [comment]
Hi @senorshaun, yes I have a test environment.  Any special instructions to update to the beta?  I'm not sure i'll have time to test right away but will get to it for sure.

**Comment by senorshaun** [comment]
looks like installing betas (any version that isn't @latest) of a plugin with HOOBS takes some work. 
They explain how here. [https://github.com/hoobs-org/HOOBS/issues/186#issuecomment-538745028](https://github.com/hoobs-org/HOOBS/issues/186#issuecomment-538745028)
the latest beta I have published is 1.5.0-beta.2 (you can check on the version tab [here](https://www.npmjs.com/package/homebridge-radiora2))

**Comment by senorshaun** [comment]
Other users have reported issues with HOOBS.
Trying installing the beta of the this homebridge plugin.
