### ISSUE TITLE
Extend Output command for Sivoia shade support

### ISSUE THREAD

**Issue by N8BrB** [senorshaun/homebridge-radiora2#28]
A big thank you for developing this plugin! It's really nice being able to integrate directly with Homekit versus using the additional gateway.

It would be really nice to also integrate some simple shade control through this  plugin.  For Sivoia shades using the Output command. 

Query shade height(%) Command - **?OUTPUT, IntegrationID, 1**
       returns ~OUTPUT,IntegrationID, %(i.e., 0.00-100.00) 

Control shade height - **#OUTPUT,IntegrationID,1,%height**
       %height is 0 for down and 100 for raised

**Comment by senorshaun** [comment]
that part is pretty straight forward. took me a couple minutes to add it in, and I have a beta that I could push, but I literally haven't compiled and tested it at all. If you know how to telnet in to your processor, it would be great if you could do a couple of commands to control your shades (using a keypad or pico remote or whatever you use, app even) and shoot the logs. I'm interested to know if the processor reports when the shade finishes moving. Also, do you have any Venetian blinds? The lift and tilt is different on those.

If I get a chance this evening, I'll make sure this beta doesn't crash homebridge and then I can either publish it to nom, if if you know how to manually modify your homebridge setup, I can publish a branch on GitHub for you to copy the files

**Comment by N8BrB** [comment]
Sure! Thanks for helping with this. I only have the sivoia shades, sorry.

Device		Integration ID
PICO		57
Shade		43

Pico (57) Open Button

GNET> ~DEVICE,57,2,3
~DEVICE,57,2,4
~OUTPUT,43,1,100.00
~OUTPUT,43,29,8
~OUTPUT,43,30,1,100.00
~OUTPUT,43,32,0,24016

After shade (43) completes opening
~OUTPUT,43,32,2,100.00

Pico (57) Close Button

~DEVICE,57,4,3
~DEVICE,57,4,4
~OUTPUT,43,1,0.00
~OUTPUT,43,29,8
~OUTPUT,43,30,1,0.00
~OUTPUT,43,32,1,24016

After shade (43) completes closing
~OUTPUT,43,32,2,0.00

Pico (57) Raise Button

~DEVICE,57,5,3
~DEVICE,57,5,4
~OUTPUT,43,1,0.45
~OUTPUT,43,29,8
~OUTPUT,43,30,1,0.45
~OUTPUT,43,32,2,0.45
~OUTPUT,43,32,2,0.45

Pico (57) Lower Button

~DEVICE,57,6,3
~OUTPUT,43,32,2,0.00
~DEVICE,57,6,4
~OUTPUT,43,1,0.00
~OUTPUT,43,29,8
~OUTPUT,43,30,1,0.00
~OUTPUT,43,32,2,0.00

**Comment by N8BrB** [comment]
What do these Actions (29,30,32) mean in the OUTPUT command response? There doesn't seem to be reference to in the Lutron Integration protocol.

**Comment by senorshaun** [comment]
That info was super helpful. I agree, thats why it's good to see what's actually being reported, because the integration guide doesn't have everything.
It looks like 30 is just a repeat of the intent (possibly a shade group kind of thing, which we don't have access to but some engineer may have tried to build it out). Not sure on 29 that looks weird
32 is the one thats very useful. that appears to be a moving notification, with component 0 as opening, 1 as closing, 2 as stopped, followed by a parameter of the intended level.
Just updated to allow the plugin to report moving state. thank you for that

**Comment by senorshaun** [comment]
Ok I have a beta published for you 1.5.9-beta.1
If you want to install that and try that out let me know. it compiled and ran for me (simulating a light as a shade). let me know if you get errors

**Comment by N8BrB** [comment]
Nice! Looking good... single tap open, single tap close, slide to position all works in Homebridge and HomeKit! Excellent work :)

There does seem to be something off with the Homebridge status, on config/load it went straight to "Closing...". Did a fully cycle on the shade it still stays at that status. On using the position slide to open, it briefly changes to "Opening" but quickly changes back back to "Closing". In Homekit it only shows Open or Closed status, no Opening or Closing. Thanks again for working on this, really appreciated.

**Comment by N8BrB** [comment]
You were definitely right about the command action 32, 0 for opening, 1 for closing, and 2 for stopped. Double checked it and is repeatable.

**Comment by senorshaun** [comment]
just pushed a beta.2 Try that out. I'm trying to play around with the PositionStatus characteristic, but again I can't really test it to know.

**Comment by N8BrB** [comment]
Just loaded, the status now shows “Closed” and “Open” states. It doesn’t seem to be showing in motion status (opening and closing).

**Comment by senorshaun** [comment]
beta.3 is out. last try lol

**Comment by N8BrB** [comment]
Thanks for this, just loaded. Interesting… so in Homebridge it still only goes from initial state to final state (Open and Closed). In HomeKit, it will go from initial state to moving state for 2 seconds, then switches to final state before the shade stops moving.

**Comment by senorshaun** [comment]
Hmm. I'm not sure what else then. It's supposed to be keying off of that status message. I can merge these changes in to production, but I'm not sure what else to do other than how it is now?
