### ISSUE TITLE
Lutron Pico Not working

### ISSUE THREAD

**Issue by nahurtado** [senorshaun/homebridge-radiora2#31]
Hello, 

I'm having issues in setting up a Lutron Pico . The Stateless device shows up in HomeKit but when I assign an action nothing happens. I know that the system is able to communicate with the Lutron Main Repeater as demonstrated by the log:

----
[28/02/2023, 10:56:38] [RadioRA2] ~DEVICE,38,10,3
[28/02/2023, 10:56:39] [RadioRA2] ~DEVICE,38,10,4
[28/02/2023, 10:56:39] [RadioRA2] Keypad 'Cubbie Lights' button #10 single pressed
[28/02/2023, 10:56:39] [RadioRA2] WARNING: Button #10 has no associated service!
----

Below is the section of the configuration that references the Pico that I'm trying to connect:

----
        {
            "id": 38,
            "name": "Cubbie Lights",
            "stateless": true,
            "buttons": [
                {
                    "id": 10,
                    "led": 10,
                    "name": "On"
                },
                {
                    "id": 11,
                    "led": 11,
                    "name": "Off"
                }
            ]
        }
----

FYI I have fans, wired keypads that are not stateless, and occupancy sensors in this config that work perfectly.

What value should I use for the LED light of a Pico?

Any ideas as to why it's not respoding?

Thank you!

**Comment by senorshaun** [comment]
interesting. I'm surprised you're the first to notice this. it's because you named the buttons (which is totally ok to do) but then the click handler wasn't expecting a name, just the ID. 
I updated the code, try loading 1.6.1-beta.9 and see if that works. I think it should work

**Comment by senorshaun** [comment]
fixed in v1.7.0 which is live
