### ISSUE TITLE
Using Keypads and Dimmers as smart switches

### ISSUE THREAD

**Issue by N8BrB** [senorshaun/homebridge-radiora2#33]
Started to notice my favorite GE halogen bulbs are no longer available and everything is LED, which means my RRD-6D’s are end of life. Since I haven’t been able to get the same soft start from the newer dimmers RRD-PRO and LED bulbs, I’m wondering if the control is better left at the bulb. 

Is there a way to have an option in Homebridge  to have the keypad buttons or dimmers/switches with neutral wiring  just be buttons similar to pico? We could use them then to control a smart bulb like Hue or Nano. Breathe some additional life to these items.

**Comment by senorshaun** [comment]
In general I'm not opposed to this idea. I'm a typically a stickler about not faking things that don't make sense, but I can see some ways to do this that do make sense. A couple questions
Your 6D dimmers have to have some load on them or they won't operate. How would you have them physically wired if you didn't want them controlling power to the smart bulb, but they still had to have a load on them?
Keypads are already set up where you can treat them as a pico. Are you talking about a hybrid keypad that doesn't use a neutral? If so, same questions as above.

I can think of issues treating it as a pico and allowing HomeKit automations to then set the value of the smart bulb. For example, tapping the raise or lower buttons would have to be a button, on and off would be a button, etc. Getting the level right I think would be an issue based on just button presses. 
Instead I think it may be better to expose something like an MQTT Broker that announces on/off/raise/lower/level/etc and then something else can consume that. Or posting web hooks. Something like that that isn't even exposed to HomeKit but rather runs entirely in homebridge.

**Comment by N8BrB** [comment]
The non neutral dimmers (rrd-6d, etc…) probably wouldn’t be good for this. I think I’ll have to take those out. The other devices with neutrals (ie -6nd, -10nd, -6na, -8ans,-f6an, -pro) should be ok without a load, just bypass the device and hard wire the bulb.

My intial thought is that this would better transitioned to Nodered, but there are some benefits doing it in Homebridge. You may have a mix of dimmer controlling reg bulbs (possibly large sets) and transition some individuals to smart bulbs. Automation may be easier for some in HomeKit.

**Comment by N8BrB** [comment]
Don’t all the keypads have neutrals?

**Comment by N8BrB** [comment]
More I think about it, the less it makes sense. I’ll remove the load and then control the bulb in nodered using hb events from the Homebridge  node. 

At some point, I’ll move the Lutron integration into nodered and do it on the backend with the bulbs also integrated into HomeKit, giving direct control of the bulb.  LED’s have really changed everything

**Comment by N8BrB** [comment]
Picked up Philips Hue system the other week and configured NodeRed to control the Hue bulbs based on HB events from the Lutron dimmer. 

Interestingly the it worked very well with dimmer from the Lutron hybrid keypad, but not so well from rrd-6nd. It seems there is a much longer delay. I think it’s a delay between the dimmer switch and Lutron repeater. I tried to zero out the fad in and out rates, thinking it may not send the status until the device reaches the on/off value, but still a noticeable delay. A little disappointing.

It does work well with dimmer from the hybrid keypad. I have 7 hue light grouped to a room on the hue hub sync’d with dimmer through rednode. On keypad button press, lights react quickly and in sync. the dimmer is revealed in HomeKit through Homebridge and allows me to control the set.

Fade in/ soft start works just like an incandescent. One hybrid keypad I have the button configured in radiora to group a few dimmers with incandescent bulbs. The hue bulbs sync’d with keypad dimmer works perfectly in sync. Can’t tell a difference!
