### ISSUE TITLE
Dimmers

### ISSUE THREAD

**Issue by BR260354** [senorshaun/homebridge-radiora2#4]
I setup in Hoobs.  The light goes on, but does not go off.  Not much else to config.  TIA!

**Comment by senorshaun** [comment]
If you manually turn off the light, does the state in HomeKit update?

**Comment by BR260354** [comment]
Looking at it in HOOBS.  When I turn off manually, it doesn't update the status unless I refresh.  After refresh, I try to turn back on via HOOBS, but it doesn't.  Turn on manually, still doesn't update the status even after refresh.

Currently I use Home Assistant to link to the radiora2 repeater.  Just looking for HOOBS/Homebridge in case I want to switch.

**Comment by BR260354** [comment]
If I restart HOOBS, if the light is on, it will go off if I click it in HOOBS.  However, it won't go back on if I click it in HOOBS.  If the status is incorrect before restart (showing on when it's off), it will still be wrong after reboot....and clicking on it doesn't do anything.  Just more clues for you.

**Comment by senorshaun** [comment]
Looks like HOOBS doesn't want to support platform style plugins that don't dynamically create their own accessories. it could be something with that?

**Comment by BR260354** [comment]
I found another plugin that worked.  RadioRA worked just fine.  Thanks!
