### ISSUE TITLE
Pico double-press not detected for certain buttons

### ISSUE THREAD

**Issue by seanwalter** [senorshaun/homebridge-radiora2#40]
This is an amazing plugin…thank you!

I am raising this issue while using version 1.7.3.

I have several 5-button pico remotes working well in homebridge throughout my home, however after several months I just started trying to use double-presses for certain functions. Double-presses appear to be recognized for 3 of the 5 pico buttons, but not the other 2 buttons. This is consistent across 2 picos I have been testing to troubleshoot the issue.

- Single-press works for all buttons

- Long press works for all buttons

- Double-press works for:
     - The top and bottom buttons (the rectangular buttons with light icons on them)
     - The round central button
 
 - Double-press does not work for either triangular button (the ones with the up/down triangle/arrow icons)

For the triangular buttons, double-press is seen as two single presses.

In my HB config I have tried using both the default double-press delay (which works for all other buttons) and also tried reducing it to 250ms. I’m happy to try other things to help troubleshoot. For now with these buttons I am using long presses as a workaround.

Thank you again for such a great plugin!

**Comment by senorshaun** [comment]
If it only doesn't work for the up and down buttons, then it may be something that Lutron is doing with just those buttons (because the would logically be pressed a lot to increase the light level of something). To test though, instead of decreasing the Click time, you would want to increase it. I don't see anything in my code that would exclude the up/down buttons to have double click events, but I don't have any pico's to test that

**Comment by seanwalter** [comment]
Sorry I went silent here…I wasn’t able to test the recommendation until last night, so wanted to close the loop for anyone else running into this issue:

Setting the Click Time to 750ms solved the problem for me. I have not tried any values between 500 (default) and 750, but at 750 I can double-tap comfortably and HomeKit sees it as such.

Thank you for your help solving this.
