### ISSUE TITLE
Autofind devices results in a JavaScript error

### ISSUE THREAD

**Issue by nshanny** [senorshaun/homebridge-radiora2#42]
Trying to use "Discover All Devices" results in nothing being returned and an infinite spinner.  Upon further inspection, the index.html is looking for "if (data.windowcoverings.length > 0 ) {", but the list is never set in server.js resulting in a type exception.  Adding         windowcoverings: this.windowcoverings as part of the return statement fixes the problem.

**Comment by senorshaun** [comment]
thanks for that 1.7.5 is live and includes that fix
