### ISSUE TITLE
Garage Door Opener

### ISSUE THREAD

**Issue by thecreativeone91** [senorshaun/homebridge-radiora2#5]
Is the RR-VCRX Supported with this plugin? Or would I need to program that to a keypad then, operate it via the keypad in home bridge? 

The Garage door and HVAC Controller are the main things that aren't supported natively via the Connect Bridge, so that's what I'm hoping to use it for.

**Comment by senorshaun** [comment]
Seems pretty easy to deal with, but what are you hoping to have exposed to HomeKit?

**Comment by cbarry** [comment]
I configured my RR-VCRX-WH like a keypad in the plugin and it seems to work fine.

RR-VCRX gets programmed like a keypad in the RadioRA2 software anyway. And as far as I can tell, the connection to visor remote seems to live entirely on the visor control receiver. From the perspective of the rest of the system, visor button presses are just keypad presses...

**Comment by senorshaun** [comment]
Ok I have an update that includes visor control recievers, with options to include inputs, buttons and outputs. the are all set up as switches in a single switching accessory. I tested out with a phantom I added to my system, but would one of you be willing to test with a real device for me?

**Comment by cbarry** [comment]
Yes, I can try it in the next few days

**Comment by cbarry** [comment]
@senorshaun is this on a branch somewhere? happy to test...

**Comment by senorshaun** [comment]
I pushed it as 1.2.0. I’m not sure if changing setpoints works properly. Let me know 

On Mar 26, 2021, at 2:38 PM, Colin Barry ***@***.***> wrote:

﻿
@senorshaun is this on a branch somewhere? happy to test...

**Comment by cbarry** [comment]
Don't know if about the setpoints (I don't have a Lutron thermostat) but the visorcontrolreceivers functionality appears to work.

**Comment by senorshaun** [comment]
@cbarry Is it the format you want? I realized that many people may have be using a visor control receiver as their garage door opener and would want it to appear in HomeKit as such. Are you in that position? If so I can work on an update that allows you to configure a visor control receiver as garage door opener, just would need you to test the open/close functionality

**Comment by senorshaun** [comment]
haven't heard back so I'm going to close out. 1.3.0 has this option
